### ISSUE TITLE
gmm_train -  multi-thread

### ISSUE THREAD

**Issue by hmkhor** [juandavm/em4gmm#64]
hi,
Seems like every time gmm_train is invoked, only one gmm is trained. 
Can em4gmm do gmm_train with multi-thread? 
If yes, when multi-thread(> 2) is enabled, how does the gmm training workload being distributed to 2 or more threads?
If no, do you have plan to enable multi-thread? Perhaps can assign one gmm training to one thread, so that every gmm_train invocation can do more than one gmm training.
Thanks.

--hm

**Comment by juandavm** [comment]
Dear --hm,

The call to gmm_train is used to train a GMM in parallel using a previously created thread pool. The way to distribute the workload is to parallelize the calculations performed at the E step of the EM algorithm, processing all the samples using blocks of data of the same size. Later, the accounts are accumulated in the M step. And so on. So, when you call the program using the "-t X" argument, you will use X threads that will speed up a lot the training of that GMM. This acceleration is noticed more as more data are available to train the GMM.

In the gmm_train.c you can observe the thread_trainer function that is executed in parallel at each thread performing the E step for each data block, and the gmm_EMtrain that assigns to the threadpool threads the thread_trainer function and perform a ligthweight M step.

You can see the threadpool at the workers.c file.

Thanks for your interest.
